// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDE7cmUoMiTJn9ZEEkpugGkEHXriaIFEs',
    appId: '1:390519998127:android:6ec71597fb5fa5e3e4f65a',
    messagingSenderId: '390519998127',
    projectId: 'cirisi',
    storageBucket: 'cirisi.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-rSfpSLKuUHDrz6svLvn-Q3aHhqvdwIQ',
    appId: '1:390519998127:web:88e4882a56489720e4f65a',
    messagingSenderId: '390519998127',
    projectId: 'cirisi',
    authDomain: 'cirisi.firebaseapp.com',
    storageBucket: 'cirisi.firebasestorage.app',
    measurementId: 'G-1Y9KMM38PF',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-rSfpSLKuUHDrz6svLvn-Q3aHhqvdwIQ',
    appId: '1:390519998127:web:205156fa2096b2a1e4f65a',
    messagingSenderId: '390519998127',
    projectId: 'cirisi',
    authDomain: 'cirisi.firebaseapp.com',
    storageBucket: 'cirisi.firebasestorage.app',
    measurementId: 'G-YLXF7YQ2SG',
  );
}
